const days: Record<string, string[]> = {
    "1/1": ["Global Family Day", "Take care of your family"],
    "10/1": ["World Hindi Day", "इस प्यारी सी भाषा को थोड़ा प्यार दो"],
    "14/1": ["World Logic Day", "Logic has taken us this far!"],
    "20/1": ["International Day of Acceptance", "Fill your hearts with acceptance, let's accept many things in life"],
    "2/2": ["World Wetlands Day", "Let's protest our water bodies, they play a big role in our environment"],
    "4/2": ["World Cancer Day", "Let take measures to prevent it and share awareness"],
    "10/2": ["World Pulses Day", "Pulses are nutritious food, play very important role in food security"],
    "13/2": ["World Radio Day", "Radio still plays a key role in disseminating information"],
    "14/2": ["Valentine's Day", "Let love prevail in our hearts"],
    "20/2": ["World Day of Social Justice", "Millions around the world are unfortunate to have a fair life. Social justice is necessary for peace, security, and development."],
    "27/2": ["World NGO Day", "NGO contribute a lot to social cause, lets recognize and honour them"],
    "1/6": ["Global Day of Parents", "Appreciate parents through out the world"],
    "2/6": ["International Sex Workers' Day", "They deserve love instead of social stigma and harassment"],
    "3/6": ["World Bicycle Day", "A simple, affordable, reliable, clean and environmentally fit sustainable means of transport"],
    "4/6": ["International Day of Innocent Children Victims of Aggression", "Let's protect childern from physical, mental and emotional abuses"],
    "5/6": ["World Environment Day", "Let's take thoughtful actions and protect the environment"],
    "7/6": ["World Food Safety Day", "Safer food, better health"],
    "8/6": ["World Oceans Day", "The ocean has been an incredibly part of our lives, let's protect it"],
    "9/6": ["World Brain Tumor Day", "Let's learn more about this illness and be well-informed"],
    "12/6": ["World Day Against Child Labour", "We must do more to combat child labor and protect children from this vice"],
    "13/6": ["International Albinism Awareness Day", "Strength beyond all odds"],
    "14/6": ["World Blood Donor Day", "Be a donor of life-saving gifts of blood and thank blood donors"],
    "15/6": ["World Elder Abuse Awareness Day", "Be aware and prevent elder abuse, they deserve love and care"],
    "16/6": ["International Day of Family Remittances", "Millions of migrant workers toil hard, so that they can create better future for their family"],
    "18/6": ["International Panic Day", "Panic, it's fine to have little bit fear, seek help if you are struggling with it"],
    "21/6": ["International Day of Yoga", "There are both physical and mental benefits of practising Yoga"],
    "23/6": ["International Olympic Day", "We should strive to become our best selves"],
    "26/6": ["International Day against Drug Abuse and Illicit Trafficking", "World free of drug abuse"],
    "30/6": ["International Asteroid Day", "Thanks to scientists who observe to protect our planet from potential impact hazards from Astroids"],
    "2/7": ["World Sports Journalists Day", "Media is our bridge to information and Journalists create those bridges"],
    "3/7": ["International Plastic Bag Free Day", "Let's eliminate the use of plastic bags"],
    "6/7": ["World Zoonoses Day", "Let's be aware of infectious diseases that can spread from animals to humans"],
    "7/7": ["Global Forgiveness Day", "A world full of healing not grudges and anger and not to burn internally"],
    "11/7": ["World Population Day", "Be aware of the pros and cons of population growth"],
    "15/7": ["World Youth Skills Day", "Let's empower young people with skills for employment and decent work"],
    "17/7": ["World Day for International Justice", "To bring justice for the victims of war crimes, crimes against humanity, and genocide"],
    "18/7": ["Nelson Mandela International Day", "An icon of peace and freedom movement. Let's empower disempowered populations across the world"],
    "20/7": ["World Chess Day", "64 squares in a chess board!"],
    "25/7": ["World Drowning Prevention Day", "No parent should experience this tragic impact of drawning"],
    "28/7": ["World Nature Conservation Day", "We can conserve nature with our simple yet impactful habits"],
    "29/7": ["International Tiger Day", "To protect and conserve the big cats, the tiger"],
    "30/7": ["International Day of Friendship", "Through friendship and developing strong ties of trust — we can contribute to global peace"],
    "31/7": ["World Ranger Day", "To celebrate the work of rangers to protect planet's natural treasures"],
    "1/8": ["World Lung Cancer Day", "Smoking is primarily responsible for lung cancer. Time to stop this bad habit!"],
    "2/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "3/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "4/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "5/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "6/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "7/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "8/8": ["International Cat Day", "Infinity symbol represents an eternal love for couples"],
    "9/8": ["International Coworking Day", "Lets gather and work together, sharing a common space"],
    "10/8": ["World Lion Day", "Let's protect the majestic big cat"],
    "12/8": ["International Youth Day", "We need focus on the difficulties that many young people are experiencing throughout the world"],
    "13/8": ["World Organ Donation Day", "Lets celebrate the virtuous act of organ donation. The donors save many lives"],
    "19/8": ["World Humanitarian Day", "Aid workers help people affected by global crises, time to recognise their selfless contributions"],
    "20/8": ["World Mosquito Day", "Causes to malaria is already known since 1897, now it's time to prevent it"],
    "21/8": ["World Senior Citizen Day", "Today is dedicated to the lives, achievements, and issues of the elders of our society"],
    "23/8": ["International Day for the Remembrance of the Slave Trade and Its Abolition", "No exploitations please!"],
    "24/8": ["International Strange Music Day", "Strange music to deal with unexepcted moments of life!"],
    "26/8": ["International Dog Day", "Caring and protecting our human's best friend"],
    "30/8": ["International Whale Shark Day", "The whale shark is known for its slow and gentle behavior, let's protect these amazing creatures"],
    "31/8": ["International Overdose Awareness Day", "Drug overdose is one of the world's worst health crises that needs awareness and prevention"],
    "2/9": ["World Coconut Day", "A rich source of elecrolytes and many antioxidants, it's water makes a great recovery drink"],
    "5/9": ["International Day of Charity", "To promote volunteer and philanthropic activities and to act with solidarity and compassion in the face of human suffering"],
    "7/9": ["International Day of Clean Air for Blue Skies", "To take action to reduce air pollution"],
    "8/9": ["International Literacy Day", "To raise awareness on the various literacy issues faced by people from different parts of the world"],
    "9/9": ["International Day to Protect Education from Attack", "To protect students, educators, and schools as education is foundation to building peaceful and resilient societies"],
    "10/9": ["World Suicide Prevention Day", "Let's promote help seeking, we can all play a role in preventing suicides"],
    "15/9": ["International Day of Democracy", "Time to appreciate our democratic societies that offer freedom"],
    "17/9": ["World Patient Safety Day", "To enhance patient safety and reduce patient harm"],
    "18/9": ["International Equal Pay Day", "Let's promote equal pay for jobs of equal value"],
    "20/9": ["International Day of University Sport", "To recognise contribution of university sport to individuals, universities and communities"],
    "21/9": ["World Alzheimer’s Day", "To raise awareness and highlight issues faced by people affected by dementia and help people live well with dementia"],
    "22/9": ["World Rose Day", "To help cancer patients to boost their spirits and keep them lively"],
    "23/9": ["International Day of Sign Languages", "Let's make an honest attempt to celebrate and accept the value of sign language"],
    "25/9": ["World Pharmacists Day", "To recognise the role of of pharmacists to boost health worldwide"],
    "26/9": ["World Contraception Day", "To raise awareness about the various methods of birth control available, in order to avoid unwanted pregnancies"],
    "27/9": ["World Tourism Day", "Tourism plays an important role in social, cultural, political and economic value"],
    "28/9": ["International Day for Universal Access to Information", "Access to quality information is vital to combat ignorance. Let's help dissemination of information to bring positive changes"],
    "29/9": ["World Heart Day", "To know it's warning signs, take steps to fight it, and to help others who may be sufferfing"],
    "30/9": ["International Translation Day", "To pay tribute to the work of language professionals, which plays an important role in bringing nations together"]
};

export default days;