const days: Record<string, string[]> = {
    "1/1": ["Global Family Day", "Take care of your family"],
    "10/1": ["World Hindi Day", "इस प्यारी सी भाषा को थोड़ा प्यार दो"],
    "14/1": ["World Logic Day", "Logic has taken us this far!"],
    "20/1": ["International Day of Acceptance", "Fill your hearts with acceptance, let's accept many things in life"],
    "2/2": ["World Wetlands Day", "Let's protest our water bodies, they play a big role in our environment"],
    "4/2": ["World Cancer Day", "Let take measures to prevent it and share awareness"],
    "10/2": ["World Pulses Day", "Pulses are nutritious food, play very important role in food security"],
    "13/2": ["World Radio Day", "Radio still plays a key role in disseminating information"],
    "14/2": ["Valentine's Day", "Let love prevail in our hearts"],
    "20/2": ["World Day of Social Justice", "Millions around the world are unfortunate to have a fair life. Social justice is necessary for peace, security, and development."],
    "27/2": ["World NGO Day", "NGO contribute a lot to social cause, lets recognize and honour them"],
    "1/6": ["Global Day of Parents", "Appreciate parents through out the world"],
    "2/6": ["International Sex Workers' Day", "They deserve love instead of social stigma and harassment"],
    "3/6": ["World Bicycle Day", "A simple, affordable, reliable, clean and environmentally fit sustainable means of transport"],
    "4/6": ["International Day of Innocent Children Victims of Aggression", "Let's protect childern from physical, mental and emotional abuses"],
    "5/6": ["World Environment Day", "Let's take thoughtful actions and protect the environment"],
    "7/6": ["World Food Safety Day", "Safer food, better health"],
    "8/6": ["World Oceans Day", "The ocean has been an incredibly part of our lives, let's protect it"],
    "9/6": ["World Brain Tumor Day", "Let's learn more about this illness and be well-informed"],
    "12/6": ["World Day Against Child Labour", "We must do more to combat child labor and protect children from this vice"],
    "13/6": ["International Albinism Awareness Day", "Strength beyond all odds"],
    "14/6": ["World Blood Donor Day", "Be a donor of life-saving gifts of blood and thank blood donors"],
    "15/6": ["World Elder Abuse Awareness Day", "Be aware and prevent elder abuse, they deserve love and care"],
    "16/6": ["International Day of Family Remittances", "Millions of migrant workers toil hard, so that they can create better future for their family"],
    "18/6": ["International Panic Day", "Panic, it's fine to have little bit fear, seek help if you are struggling with it"],
    "21/6": ["International Day of Yoga", "There are both physical and mental benefits of practising Yoga"],
    "23/6": ["International Olympic Day", "We should strive to become our best selves"],
    "26/6": ["International Day against Drug Abuse and Illicit Trafficking", "World free of drug abuse"],
    "30/6": ["International Asteroid Day", "Thanks to scientists who observe to protect our planet from potential impact hazards from Astroids"],
    "2/7": ["World Sports Journalists Day", "Media is our bridge to information and Journalists create those bridges"],
    "3/7": ["International Plastic Bag Free Day", "Let's eliminate the use of plastic bags"],
    "6/7": ["World Zoonoses Day", "Let's be aware of infectious diseases that can spread from animals to humans"],
    "7/7": ["Global Forgiveness Day", "A world full of healing not grudges and anger and not to burn internally"],
    "11/7": ["World Population Day", "Be aware of the pros and cons of population growth"],
    "15/7": ["World Youth Skills Day", "Let's empower young people with skills for employment and decent work"],
    "17/7": ["World Day for International Justice", "To bring justice for the victims of war crimes, crimes against humanity, and genocide"],
    "18/7": ["Nelson Mandela International Day", "An icon of peace and freedom movement. Let's empower disempowered populations across the world"],
    "20/7": ["World Chess Day", "64 squares in a chess board!"],
    "25/7": ["World Drowning Prevention Day", "No parent should experience this tragic impact of drawning"],
    "28/7": ["World Nature Conservation Day", "We can conserve nature with our simple yet impactful habits"],
    "29/7": ["International Tiger Day", "To protect and conserve the big cats, the tiger"],
    "30/7": ["International Day of Friendship", "Through friendship and developing strong ties of trust — we can contribute to global peace"],
    "31/7": ["World Ranger Day", "To celebrate the work of rangers to protect planet's natural treasures"]
};

export default days;