const days: Record<string, string[]> = {
    "1/1": ["Global Family Day", "Take care of your family"],
    "2/1": ["World Introvert Day", "To understand and appreciate and learn from introverts"],
    "4/1": ["World Braille Day", "To promote importance of accessibility and independence for those who are blind or visually impaired"],
    "8/1": ["World Typing Day", "Typing ensures speed, accuracy, and efficiency in documents"],
    "9/1": ["International Choreographers Day", "To appreciate and pay tribute to choreographers around the world"],
    "10/1": ["World Hindi Day", "इस प्यारी सी भाषा को थोड़ा प्यार दो"],
    "14/1": ["World Logic Day", "Logic has taken us this far!"],
    "17/1": ["International Mentoring Day", "Mentors contribute by sharing their wisdom and skills"],
    "19/1": ["World Quark Day", "To promote eating of quark a high protein, fat free, fresh soft cheese"],
    "20/1": ["International Day of Acceptance", "Fill your hearts with acceptance, let's accept many things in life"],
    "21/1": ["International Sweatpants Day", "Time to to wear your favorite, comfortable sweatpants"],
    "24/1": ["International Day of Education ", "To celebrate the role of education in global peace and sustainable development"],
    "26/1": ["International Customs Day", "To recognise role of custom in flow of goods into and out a country"],
    "27/1": ["World Breast Pumping Day", "Dedicated to breast pumping moms, as breast milk is healthier than formula milk"],
    "2/2": ["World Wetlands Day", "Let's protest our water bodies, they play a big role in our environment"],
    "4/2": ["World Cancer Day", "Let take measures to prevent it and share awareness"],
    "10/2": ["World Pulses Day", "Pulses are nutritious food, play very important role in food security"],
    "13/2": ["World Radio Day", "Radio still plays a key role in disseminating information"],
    "14/2": ["Valentine's Day", "Let love prevail in our hearts"],
    "20/2": ["World Day of Social Justice", "Millions around the world are unfortunate to have a fair life. Social justice is necessary for peace, security, and development."],
    "27/2": ["World NGO Day", "NGO contribute a lot to social cause, lets recognize and honour them"],
    "1/6": ["Global Day of Parents", "Appreciate parents through out the world"],
    "2/6": ["International Sex Workers' Day", "They deserve love instead of social stigma and harassment"],
    "3/6": ["World Bicycle Day", "A simple, affordable, reliable, clean and environmentally fit sustainable means of transport"],
    "4/6": ["International Day of Innocent Children Victims of Aggression", "Let's protect childern from physical, mental and emotional abuses"],
    "5/6": ["World Environment Day", "Let's take thoughtful actions and protect the environment"],
    "7/6": ["World Food Safety Day", "Safer food, better health"],
    "8/6": ["World Oceans Day", "The ocean has been an incredibly part of our lives, let's protect it"],
    "9/6": ["World Brain Tumor Day", "Let's learn more about this illness and be well-informed"],
    "12/6": ["World Day Against Child Labour", "We must do more to combat child labor and protect children from this vice"],
    "13/6": ["International Albinism Awareness Day", "Strength beyond all odds"],
    "14/6": ["World Blood Donor Day", "Be a donor of life-saving gifts of blood and thank blood donors"],
    "15/6": ["World Elder Abuse Awareness Day", "Be aware and prevent elder abuse, they deserve love and care"],
    "16/6": ["International Day of Family Remittances", "Millions of migrant workers toil hard, so that they can create better future for their family"],
    "18/6": ["International Panic Day", "Panic, it's fine to have little bit fear, seek help if you are struggling with it"],
    "21/6": ["International Day of Yoga", "There are both physical and mental benefits of practising Yoga"],
    "23/6": ["International Olympic Day", "We should strive to become our best selves"],
    "26/6": ["International Day against Drug Abuse and Illicit Trafficking", "World free of drug abuse"],
    "30/6": ["International Asteroid Day", "Thanks to scientists who observe to protect our planet from potential impact hazards from Astroids"],
    "2/7": ["World Sports Journalists Day", "Media is our bridge to information and Journalists create those bridges"],
    "3/7": ["International Plastic Bag Free Day", "Let's eliminate the use of plastic bags"],
    "6/7": ["World Zoonoses Day", "Let's be aware of infectious diseases that can spread from animals to humans"],
    "7/7": ["Global Forgiveness Day", "A world full of healing not grudges and anger and not to burn internally"],
    "11/7": ["World Population Day", "Be aware of the pros and cons of population growth"],
    "15/7": ["World Youth Skills Day", "Let's empower young people with skills for employment and decent work"],
    "17/7": ["World Day for International Justice", "To bring justice for the victims of war crimes, crimes against humanity, and genocide"],
    "18/7": ["Nelson Mandela International Day", "An icon of peace and freedom movement. Let's empower disempowered populations across the world"],
    "20/7": ["World Chess Day", "64 squares in a chess board!"],
    "25/7": ["World Drowning Prevention Day", "No parent should experience this tragic impact of drawning"],
    "28/7": ["World Nature Conservation Day", "We can conserve nature with our simple yet impactful habits"],
    "29/7": ["International Tiger Day", "To protect and conserve the big cats, the tiger"],
    "30/7": ["International Day of Friendship", "Through friendship and developing strong ties of trust — we can contribute to global peace"],
    "31/7": ["World Ranger Day", "To celebrate the work of rangers to protect planet's natural treasures"],
    "1/8": ["World Lung Cancer Day", "Smoking is primarily responsible for lung cancer. Time to stop this bad habit!"],
    "2/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "3/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "4/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "5/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "6/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "7/8": ["World Breastfeeding Week", "Breastfeeding is the best source of nutrition for a baby's first year of life, so lets promote it"],
    "8/8": ["International Cat Day", "Infinity symbol represents an eternal love for couples"],
    "9/8": ["International Coworking Day", "Lets gather and work together, sharing a common space"],
    "10/8": ["World Lion Day", "Let's protect the majestic big cat"],
    "12/8": ["International Youth Day", "We need focus on the difficulties that many young people are experiencing throughout the world"],
    "13/8": ["World Organ Donation Day", "Lets celebrate the virtuous act of organ donation. The donors save many lives"],
    "19/8": ["World Humanitarian Day", "Aid workers help people affected by global crises, time to recognise their selfless contributions"],
    "20/8": ["World Mosquito Day", "Causes to malaria is already known since 1897, now it's time to prevent it"],
    "21/8": ["World Senior Citizen Day", "Today is dedicated to the lives, achievements, and issues of the elders of our society"],
    "23/8": ["International Day for the Remembrance of the Slave Trade and Its Abolition", "No exploitations please!"],
    "24/8": ["International Strange Music Day", "Strange music to deal with unexepcted moments of life!"],
    "26/8": ["International Dog Day", "Caring and protecting our human's best friend"],
    "30/8": ["International Whale Shark Day", "The whale shark is known for its slow and gentle behavior, let's protect these amazing creatures"],
    "31/8": ["International Overdose Awareness Day", "Drug overdose is one of the world's worst health crises that needs awareness and prevention"],
    "2/9": ["World Coconut Day", "A rich source of elecrolytes and many antioxidants, it's water makes a great recovery drink"],
    "5/9": ["International Day of Charity", "To promote volunteer and philanthropic activities and to act with solidarity and compassion in the face of human suffering"],
    "7/9": ["International Day of Clean Air for Blue Skies", "To take action to reduce air pollution"],
    "8/9": ["International Literacy Day", "To raise awareness on the various literacy issues faced by people from different parts of the world"],
    "9/9": ["International Day to Protect Education from Attack", "To protect students, educators, and schools as education is foundation to building peaceful and resilient societies"],
    "10/9": ["World Suicide Prevention Day", "Let's promote help seeking, we can all play a role in preventing suicides"],
    "15/9": ["International Day of Democracy", "Time to appreciate our democratic societies that offer freedom"],
    "17/9": ["World Patient Safety Day", "To enhance patient safety and reduce patient harm"],
    "18/9": ["International Equal Pay Day", "Let's promote equal pay for jobs of equal value"],
    "20/9": ["International Day of University Sport", "To recognise contribution of university sport to individuals, universities and communities"],
    "21/9": ["World Alzheimer’s Day", "To raise awareness and highlight issues faced by people affected by dementia and help people live well with dementia"],
    "22/9": ["World Rose Day", "To help cancer patients to boost their spirits and keep them lively"],
    "23/9": ["International Day of Sign Languages", "Let's make an honest attempt to celebrate and accept the value of sign language"],
    "25/9": ["World Pharmacists Day", "To recognise the role of of pharmacists to boost health worldwide"],
    "26/9": ["World Contraception Day", "To raise awareness about the various methods of birth control available, in order to avoid unwanted pregnancies"],
    "27/9": ["World Tourism Day", "Tourism plays an important role in social, cultural, political and economic value"],
    "28/9": ["International Day for Universal Access to Information", "Access to quality information is vital to combat ignorance. Let's help dissemination of information to bring positive changes"],
    "29/9": ["World Heart Day", "To know it's warning signs, take steps to fight it, and to help others who may be sufferfing"],
    "30/9": ["International Translation Day", "To pay tribute to the work of language professionals, which plays an important role in bringing nations together"],
    "1/10": ["World Vegetarian Day", "A vegetarian meal better helps to preserve the Earth"],
    "2/10": ["International Day of Non-Violence", "Non-violence in pursuit of a secure and peaceful culture, non-violent thoughts and actions"],
    "3/10": ["World Temperance Day", "Excessive alcohol consumption is not good, abstain from alcohol today"],
    "4/10": ["World Animal Day", "Improving the welfare of animals around the world by preventing abuse and illegal killings"],
    "5/10": ["World Teacher's Day", "Teachers add vital contriutions and make a huge difference in many lives"],
    "6/10": ["World Cerebral Palsy Day", "Cerebral Palsy is a complex disability, let's find ways to help improve the lives of those suffering from it"],
    "8/10": ["International Podiatry Day", "Foot problems are prevalen and podiatrists around the world help advance the field"],
    "9/10": ["World Post Day", "Postal sector plays vital role in lives of businesses and individuals around the world"],
    "10/10": ["World Mental Health Day", "To raise awareness of mental health issues"],
    "11/10": ["International Day of The Girl Child", "To improve the lives of girls around the world those face unique challenges"],
    "12/10": ["World Arthritis Day", "Arthritis is the most prevalent disease in the world, early diagnosis and treatment helps"],
    "13/10": ["International Plain Language Day", "Simple and plain language is important to communicate with others"],
    "14/10": ["World Standards Day", "To pay tribute to experts who develop Internatinal standards"],
    "15/10": ["International Day of Rural Women", "Rural women play a crucial role in ensuring the sustainability of rural households and communities"],
    "16/10": ["World Food Day", "Millions across the globe do not have enough food to sustain a healthy lifestyle, we can atleast stop wasting food"],
    "17/10": ["International Day for the Eradication of Poverty", "To acknowledge the struggle of people living in poverty and to find ways to reduce global poverty"],
    "19/10": ["World Pediatric Bone and Joint Day", "Musculoskeletal disorders are any type of disease that affects the joints, ligaments, nerves, muscles, and bones"],
    "20/10": ["World Osteoporosis Day", "To raise awareness of the prevention, diagnosis, and treatment of osteoporosis, a disease in which the density and strength of the bone are reduced"],
    "21/10": ["World Iodine Deficiency Day", "Human body needs iodine to make thyroid hormones, which does several bodily functions, including heart rate, metabolism, body temperature, and muscle contractions"],
    "22/10": ["International Stuttering Awareness Day", "To change public attitudes and eliminate societal discrimination toward people who stutter"],
    "23/10": ["International Snow Leopard Day", "Often called as the 'ghosts of the mountains', snow leopards are endangered species"],
    "24/10": ["World Polio Day", "To raise awareness and make efforts to make the world polio-free"],
    "25/10": ["International Artist’s Day", "To honor honors artists and all the contributions they make"],
    "27/10": ["World Occupational Therapy Day", "Occupational therapists provide treatment to injured or disabled patients and children with special needs"],
    "28/10": ["International Animation Day", "A day to celebrate all aspects of animation"],
    "29/10": ["World Stroke Day", "To raise awareness of the prevention and treatment of strokes"],
    "31/10": ["World Savings Day", "Saving has a great impact on financial stability and global economy, 'a penny saved is a penny earned'"],
    "1/11": ["World Vegan Day", "To raise education and awareness about vegan diets that excludes meat, eggs, dairy products, and honey"],
    "3/11": ["World Jellyfish Day", "Jellyfish are older than dinosaurs and have been around for over 500 million years"],
    "5/11": ["World Tsunami Awareness Day", "To raise awareness and share innovative approaches to risk reduction as tsunamis can be very destructive"],
    "7/11": ["International Day of Medical Physics", "Physics greatly benefits in radiology and nuclear medicine which aids in various diagnostic tests"],
    "8/11": ["World Radiography Day", "To educate general public about X-rays and radiation safety"],
    "9/11": ["World Adoption Day", "To help raise awareness for adoption and to provide a family for every child"],
    "10/11": ["International Accounting Day", "Accountants help make businesses and organizations thrive"],
    "11/11": ["International Origami Day", "To celebrate an unique art from using paper"],
    "12/11": ["World Pneumonia Day", "Pneumonia is an infection that causes the air sacs in the lungs to become filled with fluid or pus. One of the major risk factors for pneumonia is air pollution"],
    "13/11": ["World Kindness Day", "To raise awareness to spread kindness and compassion"],
    "14/11": ["World Diabetes Day", "To raise awanerss about diabetes a leading cause of blindness, amputation, heart disease, and kidney disease"],
    "16/11": ["International Day for Tolerance", "To respect, accept, and appreciate the rich diversity of our world’s cultures and to coexist peacefully"],
    "17/11": ["International Students Day", "To raise voices for equal access to education"],
    "19/11": ["International Men’s Day", "To lead by example, help to create a fair and safe society and teach young boys the values, character, and responsibilities of being a man"],
    "20/11": ["World Children’s Day", "Children deserve the right to life, health, education, and the right to play. To promote the welfare of children around the world"],
    "21/11": ["World Hello Day", "To promote the role of communication for preserving peace and to settle conflicts. Say hello!"],
    "23/11": ["Fibonacci Day", "To do fun activities utilizing the Fibonacci sequence"],
    "25/11": ["International Day for the Elimination of Violence Against Women", "To remove the silence, stigma, and shame surrounding acts of violence against women"],
    "1/12": ["World AIDS Day", "World AIDS Day was the first ever global health day founded in 1988, since then much has been done to prevent AIDS"],
    "2/12": ["International Day for the Abolition of Slavery", "Surprisingly slavery still exists in modern forms in - Forced labor, Child labor, Human Trafficking"],
    "3/12": ["International Day of Persons with Disabilities", "To promote the rights and well-being of persons with disabilities"],
    "4/12": ["World Wildlife Conservation Day", "To spread awareness about preserving and protecting the natural world and its inhabitants"],
    "5/12": ["World Soil Day", "To raise awareness about soil degradation"],
    "9/12": ["International Anti-corruption Day", "Every year trillions of fund lost to corruption, time to battle against this crime thru innovation"],
    "10/12": ["International Animal Rights Day", "Animals can feel pain and perceive feelings so they have rights to kindness and respect"],
    "11/12": ["International Mountain Day", "Conservation of mountaions are extremely important, contribute to the cause by reducing carbon footprint"],
    "12/12": ["International Day of Neutrality", "To promote neutrality among countries"],
    "13/12": ["International Universal Health Coverage Day", "A country with UHC provides quality medical care to all of its citizens, regardless of their ability to pay"],
    "15/12": ["International Tea Day", "Tea is the most popular beverage consumed, yet wages are low for tea workers"],
    "18/12": ["International Migrants Day", "To recognise the contributions and efforts of migrants around the world"],
    "20/12": ["International Human Solidarity Day", "To promote awareness of shared interests and values that create a sense of unity among societies"],
};

export default days;